---
title: "Conclusions"
---
We do see that there are fundamental differences between the candidates and the rhetoric and speech style used. Whether it was the emotional and social connotation surround particular words or the topics that were used. Further research needs to occur to be able to substantially link these ideas to the outcome of the election, but it does seem plausible that what allowed Donald Trump to win the election was the significant amount of campaigning he was able to do in September and October, an emphasis on employment rhetoric, and using language that implied a sense of negativity that countered the polished appearances of the candidates he competed against. Further in his rhetoric, it seems very derisive in drawing groups and boundaries, dividing individuals and attempting to relate to each of these groups. I believe that this had the effect of a divide and conquer- type mindset. By being able to pit people against one another, he was able to then elicit certain emotions and relate particular policy to individual groups. It may be due to his years of being in the public eye, but Donald Trump was able to relate and leave a lasting impression with those he interacted with.  Essentially, he was able to outperform the other candidates, and in doing so, win the election. In future research, we would like to be able to provide more systematic metrics and increase the data over multiple elections to examine any patterns that seem of rhetoric that seem essential to the outcome of a given election.  


I would like to acknowledge and thank those associated with the American Presidency Project (http://www.presidency.ucsb.edu/index.php) for meticulously documenting the speeches from all candidates over the course of the election.

I would also like to thank those who developed the word clouds package that allowed for the beautiful word clouds that we were able to produce.

If you have any questions or comments about this project, feel free to contact me at brianpennington11@gmail.com. All code and data is openly available on the followin github: https://github.com/brianp1/2016_Campaign_Speeches


